<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="TestDriver.TestExecutionDriver" tests="29" time="12231.041" ignored="0" failures="4" timestamp="05 Jan 2018 15:10:10 GMT" skipped="0" hostname="C4LAP149" errors="0">
  <testcase name="TestCaseExecution" time="512.486" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="565.535" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="371.608" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="415.974" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="285.372" classname="TestDriver.TestExecutionDriver">
    <failure type="java.lang.AssertionError" message=" failed">
      <![CDATA[java.lang.AssertionError:  failed
	at org.testng.Assert.fail(Assert.java:94)
	at DUMMYDELETEIT.genericDriver.CV_ProductBasketAddition(genericDriver.java:189)
	at TestDriver.TestExecutionDriver.TestCaseExecution(TestExecutionDriver.java:127)
	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- TestCaseExecution -->
  <testcase name="TestCaseExecution" time="430.802" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="328.449" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="333.851" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="384.327" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="280.075" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="322.891" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="773.201" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="501.348" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="135.858" classname="TestDriver.TestExecutionDriver">
    <failure type="java.lang.AssertionError" message=" failed">
      <![CDATA[java.lang.AssertionError:  failed
	at org.testng.Assert.fail(Assert.java:94)
	at DUMMYDELETEIT.genericDriver.OI_ProductBasketConfiguration(genericDriver.java:349)
	at TestDriver.TestExecutionDriver.TestCaseExecution(TestExecutionDriver.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- TestCaseExecution -->
  <testcase name="TestCaseExecution" time="221.635" classname="TestDriver.TestExecutionDriver">
    <failure type="java.lang.AssertionError" message=" failed">
      <![CDATA[java.lang.AssertionError:  failed
	at org.testng.Assert.fail(Assert.java:94)
	at DUMMYDELETEIT.genericDriver.CI_PowerSpot_ProductBasketAddition(genericDriver.java:280)
	at TestDriver.TestExecutionDriver.TestCaseExecution(TestExecutionDriver.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- TestCaseExecution -->
  <testcase name="TestCaseExecution" time="497.282" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="549.143" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="449.232" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="455.246" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="391.806" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="282.081" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="380.594" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="393.519" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="582.953" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="397.397" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="623.851" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="566.293" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="769.571" classname="TestDriver.TestExecutionDriver"/>
  <testcase name="TestCaseExecution" time="28.661" classname="TestDriver.TestExecutionDriver">
    <failure type="java.lang.AssertionError" message=" failed">
      <![CDATA[java.lang.AssertionError:  failed
	at org.testng.Assert.fail(Assert.java:94)
	at DUMMYDELETEIT.genericDriver.genericNewLeadCreation(genericDriver.java:109)
	at TestDriver.TestExecutionDriver.TestCaseExecution(TestExecutionDriver.java:113)
	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- TestCaseExecution -->
</testsuite> <!-- TestDriver.TestExecutionDriver -->
